### ISSUE TITLE
도서 구입자입니다. 질문있어요

### ISSUE THREAD

**Issue by bin9000** [finterstellar/quant_machine#1]
안녕하세요? 
슬기로운 퀀트투자로 입문했는데 질문있습니다.

df = fs.backtest(signal=signal, data=data, m=2, cost=0.001) 에 대해 질문있어요

이 코드에서 m=2 라는 뜻을 정확히 모르겠어요
매 분기의 Price_M2 (2,5,8,11월 말) 마다, 리밸런싱(기존 종목 매도하고, 새로운 종목 매수)한다는 뜻인가요?

즉, 2020Q3 의 재무제표로 분석하여 2020년 11월 말에 리밸런싱 한다는 뜻이죠?

백테스트는 위와 같이 하고, 
그럼 실제로 매수/매도 할때는 재무제표 나오는 날 해당 주가를 기준으로 리밸런싱을 수행하면 되는거죠?

**Comment by finterstellar** [comment]
I guess you already found the concept. You may find more details from p. 145 of the book.
In addition, this is not a place for Q&A. Use the official site for any questions.

**Comment by bin9000** [comment]
> I guess you already found the concept. You may find more details from p. 145 of the book. In addition, this is not a place for Q&A. Use the official site for any questions.

Thanks for your reply. I will delete this question. Would you let me know the official site? I couldn't find it.
